. .\`_generate.ps1

# Biologia
MakeArticle "biologia" "sistema-digestorio.html" "biologia" "Biologia" "Sistema Digestório" "Sistema Digestório" "Da boca ao intestino, entenda como seu corpo processa os alimentos em 1 minuto." "75" "<p>O <strong>sistema digestório</strong> transforma os alimentos em nutrientes que as células podem usar. O processo envolve digestão mecânica e química.</p><h2>Caminho do Alimento</h2><p><strong>1. Boca:</strong> Mastigação (mecânica) e saliva (química - amilase salivar).</p><p><strong>2. Faringe e Esôfago:</strong> Conduzem o alimento ao estômago por movimentos peristálticos.</p><p><strong>3. Estômago:</strong> O suco gástrico (ácido) e a enzima pepsina digerem proteínas.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><p><strong>4. Intestino Delgado:</strong> Principal local de mágica. Recebe bile (fígado) para emulsificar gorduras e suco pancreático. Aqui ocorre a maior absorção de nutrientes.</p><p><strong>5. Intestino Grosso:</strong> Absorção de água e formação das fezes.</p>" "<ul><li><strong>Boca:</strong> Início da digestão de carboidratos.</li><li><strong>Estômago:</strong> Início da digestão de proteínas.</li><li><strong>Intestino Delgado:</strong> Fim da digestão e absorção.</li><li><strong>Fígado:</strong> Produz a bile, que não tem enzimas, mas quebra gorduras.</li></ul>" "Onde ocorre a maior parte da absorção de nutrientes?" "A maior absorção de nutrientes ocorre no <strong>Intestino Delgado</strong>, devido às vilosidades e microvilosidades que aumentam a área de contato." "Para que serve a bile?" "A bile é produzida pelo fígado e age como um 'detergente' no intestino delgado, emulsificando (quebrando em gotas menores) as gorduras para facilitar a digestão." "🧬"

# Química
$quimica_arts = @(
    @{file="tabela-periodica.html"; title="Tabela Periódica"; desc="Famílias, períodos e elementos — o mapa da química."; xp="50"},
    @{file="ligacoes-quimicas.html"; title="Ligações Químicas"; desc="Iônica, Covalente, Metálica — como os átomos se unem."; xp="75"},
    @{file="reacoes-quimicas.html"; title="Reações Químicas"; desc="Síntese, análise e trocas — transformando a matéria."; xp="50"}
)
MakeLanding "quimica" "Química" "quimica" "Reações, elementos e a composição do universo — mastigado em 1 minuto." $quimica_arts "Descubra o mundo atômico" "Simulados e missões incríveis no Web App." '<svg viewBox="0 0 36 36" fill="none" style="width:48px;height:48px;vertical-align:middle;margin-right:8px"><path d="M14 4h8v12l6 14H8l6-14V4z" fill="#E67E22" opacity="0.2" stroke="#E67E22" stroke-width="2"/><line x1="12" y1="4" x2="24" y2="4" stroke="#E67E22" stroke-width="2"/><circle cx="18" cy="26" r="2" fill="#E67E22" opacity="0.5"/></svg>'

MakeArticle "quimica" "tabela-periodica.html" "quimica" "Química" "Tabela Periódica" "Tabela Periódica" "Entenda os períodos e famílias da Tabela Periódica em 1 minuto." "50" "<p>A <strong>Tabela Periódica</strong> organiza todos os elementos químicos conhecidos em ordem crescente de <strong>Número Atômico (Z)</strong> (quantidade de prótons).</p><h2>Organização</h2><p><strong>Períodos (Linhas Horizontais):</strong> São 7. Indicam o número de <strong>camadas eletrônicas</strong> que o elemento possui.</p><p><strong>Famílias ou Grupos (Colunas Verticais):</strong> São 18. Elementos da mesma família possuem <strong>propriedades químicas semelhantes</strong> e o mesmo número de elétrons na camada de valência.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Classificação Básica</h2><p><strong>Metais:</strong> Maioria. Bons condutores, sólidos (exceto Hg), tendem a doar elétrons.</p><p><strong>Ametais (Não-Metais):</strong> Maus condutores, tendem a receber elétrons.</p><p><strong>Gases Nobres (Família 18):</strong> Estáveis, não se misturam facilmente com outros elementos.</p>" "<ul><li>Ordem crescente de <strong>Número Atômico (Z)</strong>.</li><li><strong>Períodos</strong> = camadas eletrônicas.</li><li><strong>Famílias</strong> = propriedades semelhantes (valência).</li><li>A maioria dos elementos são <strong>Metais</strong>.</li></ul>" "O que é Número Atômico?" "O Número Atômico (Z) é a quantidade de <strong>prótons</strong> no núcleo de um átomo e é a 'identidade' do elemento químico." "Por que os gases nobres são 'nobres'?" "Os gases nobres possuem a <strong>camada de valência completa</strong> (geralmente 8 elétrons, a regra do octeto), o que os torna muito estáveis e pouco reativos com outros elementos." "⚗️"

MakeArticle "quimica" "ligacoes-quimicas.html" "quimica" "Química" "Ligações Químicas" "Ligações Químicas" "Iônica, Covalente, Metálica — como os átomos se unem. Microlearning em 1 minuto." "75" "<p>Para alcançarem a estabilidade dos gases nobres (8 elétrons na camada de valência), os átomos precisam se unir através de <strong>Ligações Químicas</strong>.</p><h2>1. Ligação Iônica</h2><p>Ocorre entre <strong>Metal e Ametal</strong>. Há transferência definitiva de elétrons. O metal doa (vira cátion +) e o ametal recebe (vira ânion -). Ex: NaCl (Sal de cozinha).</p><h2>2. Ligação Covalente</h2><p>Ocorre entre <strong>Ametal e Ametal</strong> (ou Hidrogênio). Há <strong>compartilhamento</strong> de elétrons. Forma moléculas. Ex: H2O, CO2, O2.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>3. Ligação Metálica</h2><p>Ocorre entre <strong>Metais</strong>. Forma a 'teia eletrônica' ou 'mar de elétrons', elétrons livres vagando entre os cátions metálicos. Garante condutividade. Ex: Ouro, Ferro.</p>" "<ul><li><strong>Iônica:</strong> Metal + Ametal → <strong>Doa/Recebe</strong> elétrons.</li><li><strong>Covalente:</strong> Ametal + Ametal → <strong>Compartilha</strong> elétrons.</li><li><strong>Metálica:</strong> Metal + Metal → <strong>Mar de elétrons</strong>.</li></ul>" "O que é a regra do octeto?" "É a tendência dos átomos de possuírem <strong>8 elétrons na sua camada de valência</strong> para atingirem estabilidade, semelhante aos gases nobres." "A água é iônica ou covalente?" "Sendo formada por Hidrogênio e Oxigênio (um ametal), a água (H2O) realiza ligações do tipo <strong>Covalente</strong> (compartilhamento)." "⚗️"

MakeArticle "quimica" "reacoes-quimicas.html" "quimica" "Química" "Reações Químicas" "Reações Químicas" "Síntese, análise e trocas — transformando a matéria. Aprenda rápido." "50" "<p>Uma <strong>Reação Química</strong> ocorre quando substâncias iniciais (<strong>Reagentes</strong>) se transformam em novas substâncias (<strong>Produtos</strong>).</p><h2>Tipos de Reações</h2><p><strong>1. Síntese ou Adição:</strong> Duas ou mais substâncias se unem para formar uma só. (A + B → AB)</p><p><strong>2. Análise ou Decomposição:</strong> Uma única substância se divide em várias. (AB → A + B)</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><p><strong>3. Simples Troca ou Deslocamento:</strong> Uma substância simples troca de lugar com um elemento de uma substância composta. (A + BC → AC + B)</p><p><strong>4. Dupla Troca:</strong> Duas substâncias compostas trocam partes entre si. (AB + CD → AD + CB)</p>" "<ul><li><strong>Reagentes</strong> à esquerda da seta, <strong>Produtos</strong> à direita.</li><li><strong>Síntese:</strong> junta tudo.</li><li><strong>Decomposição:</strong> quebra em partes.</li><li><strong>Dupla Troca:</strong> troca de parceiros.</li></ul>" "Como sei que houve uma reação química?" "Evidências comuns incluem: liberação de gás, mudança de cor, mudança de cheiro, formação de precipitado (sólido) ou liberação/absorção de calor/luz." "O que é a lei de Lavoisier?" "No princípio da Conservação das Massas, 'Na natureza, nada se cria, nada se perde, tudo se transforma'. A massa total dos reagentes é igual à massa total dos produtos." "⚗️"

# Física
$fisica_arts = @(
    @{file="leis-de-newton.html"; title="Leis de Newton"; desc="Inércia, Dinâmica e Ação e Reação."; xp="75"},
    @{file="velocidade-e-aceleracao.html"; title="Velocidade e Aceleração"; desc="A diferença entre MRU e MRUV de modo prático."; xp="50"},
    @{file="energia-e-trabalho.html"; title="Energia e Trabalho"; desc="Força e deslocamento e suas relações."; xp="50"}
)
MakeLanding "fisica" "Física" "fisica" "Mecânica, energia e leis do universo sem complicação." $fisica_arts "Domine a Mecânica" "Física ficou fácil. Desafios completos esperam você." '<svg viewBox="0 0 36 36" fill="none" style="width:48px;height:48px;vertical-align:middle;margin-right:8px"><path d="M18 4L8 18h6l-2 14L28 16h-7l3-12z" fill="#00BCD4" opacity="0.2" stroke="#00BCD4" stroke-width="2"/></svg>'

MakeArticle "fisica" "leis-de-newton.html" "fisica" "Física" "As 3 Leis de Newton" "Leis de Newton" "Inércia, Princípio Fundamental da Dinâmica e Ação e Reação explicadas em 1 min." "75" "<p>As três Leis de Newton formam a base da <strong>mecânica clássica</strong>.</p><h2>1ª Lei — Inércia</h2><p>Todo corpo continua em seu estado de repouso ou de movimento retilíneo uniforme (MRU) a menos que seja forçado a mudar aquele estado por forças aplicadas sobre ele. <em>(Por isso usamos cinto de segurança).</em></p><h2>2ª Lei — Princípio Fundamental da Dinâmica</h2><p>A força resultante que atua num corpo é diretamente proporcional à sua massa vezes a sua aceleração: <strong>F = m · a</strong></p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>3ª Lei — Ação e Reação</h2><p>A toda ação há sempre uma reação oposta e de igual intensidade. As forças atuam em <strong>corpos diferentes</strong>, portanto, não se anulam. <em>(O pé chuta a bola, a bola 'chuta' o pé).</em></p>" "<ul><li><strong>Inércia:</strong> tendência de manter o movimento atual.</li><li><strong>Massa:</strong> é a medida da inércia.</li><li><strong>F = m · a</strong> (Força = massa × aceleração).</li><li><strong>Ação e Reação:</strong> mesma direção, sentidos opostos, corpos diferentes.</li></ul>" "O que acontece se a Força Resultante for zero?" "Pela 1ª Lei, se a força resultante é zero, a aceleração também é zero. O objeto estará em repouso absoluto ou em Movimento Retilíneo Uniforme (velocidade constante)." "Por que forças de ação e reação não se anulam?" "Porque elas são aplicadas em objetos diferentes. A força que eu faço na parede age na parede. A força que a parede faz em mim age em mim." "⚡"

MakeArticle "fisica" "velocidade-e-aceleracao.html" "fisica" "Física" "Velocidade e Aceleração" "Velocidade e Aceleração" "MRU vs MRUV e a diferença entre velocidade e aceleração em 1 minuto." "50" "<p>Na Cinemática, os conceitos costumam confundir, mas são muito simples.</p><h2>Velocidade: O Ritmo do Movimento</h2><p>É a variação de espaço em um certo tempo (v = ΔS/Δt). Indica quão rápido você vai de A até B.</p><p><strong>MRU (Movimento Retilíneo Uniforme):</strong> Velocidade é constante. Aceleração é <strong>zero</strong>.</p><h2>Aceleração: A Mudança de Ritmo</h2><p>Aceleração muda a velocidade. (a = Δv/Δt).</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><p><strong>MRUV (Movimento Retilíneo Uniformemente Variado):</strong> A velocidade aumenta ou diminui de forma constante (existe uma aceleração e ela não muda ao longo do tempo). A queda livre é um MRUV (acelerado pela gravidade ~10m/s²).</p>" "<ul><li><strong>Velocidade:</strong> metros caminhados por segundo (m/s).</li><li><strong>Aceleração:</strong> o quanto a velocidade sobe/desce (m/s²).</li><li><strong>MRU:</strong> v = constante, a = 0.</li><li><strong>MRUV:</strong> v = muda, a = constante (não nula).</li></ul>" "Como calcular velocidade média?" "Velocidade Média (Vm) = Variação de Espaço (ΔS - a distância) dividida pela Variação de Tempo (Δt)." "Dá pra ter aceleração negativa?" "Sim, e a chamamos de desaceleração ou frenagem (movimento retardado), onde a velocidade do corpo está diminuindo ao longo do tempo." "⚡"

MakeArticle "fisica" "energia-e-trabalho.html" "fisica" "Física" "Energia e Trabalho" "Energia e Trabalho" "Força, deslocamento e como a energia atua na física." "50" "<p>Em Física, <strong>Trabalho (T ou W)</strong> é a transferência de energia realizada por uma força quando ela produz o <strong>deslocamento</strong> de um corpo (T = F · d).</p><h2>Energia Mecânica (EM)</h2><p>É a capacidade de realizar trabalho. A Energia Mecânica se divide em duas partes principais:</p><p><strong>Energia Cinética (Ec):</strong> Energia do <strong>movimento</strong>. Quanto maior a velocidade e massa do objeto, maior ela é. (Ec = mv²/2)</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><p><strong>Energia Potencial (Ep):</strong> Energia <strong>armazenada</strong>. Pode ser Gravitacional (altura — Epg = mgh) ou Elástica (mola / elástico estendido).</p><h2>Conservação da Energia</h2><p>Sistema conservativo: a Energia Mecânica Inicial é igual à Energia Mecânica Final (EM = Ec + Ep = constante). O movimento se transforma: altura vira velocidade na montanha russa.</p>" "<ul><li>Sem deslocamento na mesma direção da força = <strong>Sem Trabalho</strong>.</li><li><strong>Cinética:</strong> Velocidade.</li><li><strong>Potencial:</strong> Altura ou Mola.</li><li>A energia mecânica total se conserva em quedas (sem atrito).</li></ul>" "Trabalho pode ser nulo (zero) com força aplicada?" "Sim. Se você empurrar uma parede e ela não sair do lugar (nenhum deslocamento), o Trabalho realizado foi zero, embora você gaste energia corporal." "Energia cinética muda mais pela massa ou pela velocidade?" "Pela velocidade, porque na fórmula ela é elevada ao quadrado (v²). Dobrar a massa dobra a energia, mas dobrar a velocidade quadruplica a energia!" "⚡"
