. .\`_generate.ps1

# Inglês
$ingles_arts = @(
    @{file="simple-present.html"; title="Simple Present"; desc="Fatos e rotinas em inglês."; xp="50"},
    @{file="simple-past.html"; title="Simple Past"; desc="Como falar sobre o passado do jeito certo."; xp="50"},
    @{file="modal-verbs.html"; title="Modal Verbs"; desc="Can, Could, Should e Must em detalhes."; xp="75"}
)
MakeLanding "ingles" "Inglês" "ingles" "Gramática e vocabulário sem complicação. Seu inglês levado a sério." $ingles_arts "Do you speak English?" "Pratique reading e grammar no Web App agora." '<svg viewBox="0 0 36 36" fill="none" style="width:48px;height:48px;vertical-align:middle;margin-right:8px"><circle cx="18" cy="18" r="14" fill="#1ABC9C" opacity="0.15" stroke="#1ABC9C" stroke-width="2"/><text x="18" y="23" text-anchor="middle" fill="#1ABC9C" font-size="13" font-weight="bold" font-family="Outfit">EN</text></svg>'

MakeArticle "ingles" "simple-present.html" "ingles" "Inglês" "Simple Present" "Simple Present" "Como usar o Simple Present para fatos e rotina em inglês." "50" "<p>O <strong>Simple Present</strong> é usado para descrever ações habituais, rotinas e fatos universais.</p><h2>Estrutura Básica</h2><p>Na afirmativa, usamos o verbo na base. <em>Ex: I play soccer.</em></p><p>Atenção: Na 3ª pessoa do singular (He, She, It), adicionamos <strong>-s, -es ou -ies</strong> ao verbo. <em>Ex: He play<strong>s</strong> soccer.</em></p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Negativa e Interrogativa</h2><p>Na negativa, usamos os auxiliares <strong>don't</strong> ou <strong>doesn't</strong> (para He/She/It), e o verbo principal volta à base. <em>Ex: She doesn't play soccer.</em></p><p>Na interrogativa, colocamos <strong>Do</strong> ou <strong>Does</strong> no início da frase. <em>Ex: Do you like pizza?</em></p>" "<ul><li>Fatos e Rotina = Simple Present.</li><li><strong>He, She, It</strong> afirmativa: Verbo + s/es/ies.</li><li><strong>Negativa:</strong> don't / doesn't.</li><li><strong>Interrogativa:</strong> Do / Does.</li></ul>" "O verbo muda na negativa com He/She/It?" "Não! A regra do 's' só vale para frases AFIRMATIVAS com He, She ou It. Na negativa, o 'doesn't' rouba a conjugação, e o verbo principal fica normal." "Quais verbos recebem -es?" "Verbos terminados em -o, -s, -sh, -ch, -x, -z. Exemplo: go -> goes, watch -> watches." "🌍"

MakeArticle "ingles" "simple-past.html" "ingles" "Inglês" "Simple Past" "Simple Past" "O passado simples em inglês. Aprenda as regras." "50" "<p>O <strong>Simple Past</strong> é usado para ações que começaram e terminaram em um período de tempo definido no passado.</p><h2>Verbos Regulares</h2><p>Os verbos regulares formam o passado adicionando <strong>-ed</strong>. <em>Ex: work -> worked, play -> played.</em></p><h2>Verbos Irregulares</h2><p>Os verbos irregulares não seguem a regra do '-ed' e possuem formas próprias. <em>Ex: go -> went, see -> saw, buy -> bought.</em> Tem que memorizar!</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Negativa e Interrogativa</h2><p>Assim como no presente, o passado precisa de um auxiliar para negar e perguntar. Usamos o <strong>Did</strong>.</p><p>Negativa: <strong>didn't</strong>. <em>Ex: I didn't go to the party.</em> (Observe que o 'go' não fica 'went', pois o 'didn't' já indica passado).</p><p>Interrogativa: <strong>Did</strong> no início. <em>Ex: Did you see him?</em></p>" "<ul><li>Ações terminadas no passado.</li><li>Regulares: Verbo + <strong>ed</strong>.</li><li>Irregulares: Forma especial (go -> went).</li><li>Auxiliar do passado: <strong>Did</strong> / <strong>Didn't</strong> (verbo volta ao normal).</li></ul>" "O que significa 'yesterday' e 'last week'?" "São advérbios de tempo essenciais para o Simple Past. 'Yesterday' = ontem. 'Last week' = semana passada. Eles definem o tempo concluído no passado." "Por que usamos 'did' e o verbo normal?" "Porque em inglês não repetimos a marcação de tempo. O 'did' já mostra que é passado, então o verbo principal não precisa terminar em '-ed' ou ser irregular na frase." "🌍"

MakeArticle "ingles" "modal-verbs.html" "ingles" "Inglês" "Modal Verbs" "Modal Verbs" "Can, Could, Should e Must: como e quando usar." "75" "<p>Os <strong>Modal Verbs</strong> são verbos auxiliares que mudam o sentido do verbo principal, expressando habilidade, possibilidade, permissão ou obrigação.</p><h2>Características Gerais</h2><p>1. Eles nunca mudam (não recebem 's' na terceira pessoa).</p><p>2. São seguidos pelo verbo principal na forma base, SEM o 'to'.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Os Principais</h2><p><strong>CAN:</strong> Habilidade ou permissão informal. <em>Ex: I can swim. Can I go to the bathroom?</em></p><p><strong>COULD:</strong> Habilidade no passado ou pedido mais educado. <em>Ex: Could you help me, please?</em></p><p><strong>SHOULD:</strong> Conselho (deveria). <em>Ex: You should study more.</em></p><p><strong>MUST:</strong> Obrigação forte. <em>Ex: You must wear a seatbelt.</em></p>" "<ul><li>Não recebem 's' no He/She/It.</li><li>Verbo da frente fica sem o 'to'.</li><li>Can = habilidade/permissão.</li><li>Must = obrigação.</li><li>Should = conselho.</li></ul>" "Qual a diferença entre 'May' e 'Can' para permissão?" "'May' é mais formal e polido do que 'Can'. Dizer 'May I go to the bathroom?' é mais formal do que 'Can I go...?'." "Como faríamos a forma negativa dos Modals?" "Eles não precisam de auxiliares como 'don't'. Basta adicionar 'not' a eles: cannot (can't), could not (couldn't), should not (shouldn't), must not (mustn't)." "🌍"

# Filosofia
$filosofia_arts = @(
    @{file="socrates.html"; title="Sócrates e o Método"; desc="Só sei que nada sei: a ironia e a maiêutica."; xp="50"},
    @{file="mito-da-caverna.html"; title="O Mito da Caverna"; desc="Platão e o mundo das ideias."; xp="75"},
    @{file="etica-e-moral.html"; title="Ética vs Moral"; desc="Diferenças cruciais entre os dois conceitos."; xp="50"}
)
MakeLanding "filosofia" "Filosofia" "filosofia" "Os grandes pensadores e ideias que moldaram o mundo." $filosofia_arts "Pense fora da caixa" "Teste seus conhecimentos filosóficos." '<svg viewBox="0 0 36 36" fill="none" style="width:48px;height:48px;vertical-align:middle;margin-right:8px"><circle cx="18" cy="14" r="8" fill="#607D8B" opacity="0.15" stroke="#607D8B" stroke-width="2"/><path d="M18 22v8M14 30h8" stroke="#607D8B" stroke-width="2" stroke-linecap="round"/><circle cx="18" cy="14" r="3" fill="#607D8B" opacity="0.4"/></svg>'

MakeArticle "filosofia" "socrates.html" "filosofia" "Filosofia" "Sócrates e o Método Socrático" "Sócrates" "Ironia, maiêutica e a célebre frase 'Só sei que nada sei'." "50" "<p>Sócrates foi um filósofo grego que não deixou nada escrito. Ele acreditava que o conhecimento deveria ser buscado através do diálogo.</p><h2>'Só sei que nada sei'</h2><p>A sabedoria socrática baseia-se no reconhecimento da própria ignorância. Reconhecer que não se sabe é o primeiro passo para o conhecimento.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Método Socrático (Diálogo)</h2><p><strong>Ironia:</strong> Fase onde Sócrates fazia perguntas para fingir ignorância sobre o assunto e demonstrar que seu interlocutor, que se considerava sábio, na verdade era ignorante e confuso.</p><p><strong>Maiêutica (Parto das Ideias):</strong> Através de mais perguntas, levava a pessoa a 'dar à luz' ao próprio conhecimento que estava latente dentro dela.</p>" "<ul><li>Reconhecimento da ignorância é o princípio do filosofar.</li><li><strong>Ironia:</strong> quebrar a falsa sabedoria.</li><li><strong>Maiêutica:</strong> gerar novas ideias de dentro para fora.</li><li>Foco na busca pela verdade e ética.</li></ul>" "O que Sócrates escreveu?" "Nada! Tudo o que sabemos sobre ele nos foi relatado através dos textos de seus discípulos, principalmente Platão." "Por que Sócrates foi condenado à morte?" "Ele foi acusado de corromper a juventude de Atenas e de não acreditar nos deuses da cidade. Ele foi obrigado a beber cicuta (um veneno)." "💡"

MakeArticle "filosofia" "mito-da-caverna.html" "filosofia" "Filosofia" "Mito da Caverna" "Mito da Caverna" "Alegoria de Platão sobre ignorância e a iluminação pelo conhecimento." "75" "<p>O <strong>Mito da Caverna</strong> é uma alegoria criada por Platão no livro 'A República'. É a obra mais famosa da filosofia clássica.</p><h2>A Alegoria</h2><p>Prisioneiros estão acorrentados em uma caverna desde o nascimento. Eles só podem olhar para a parede ao fundo, onde veem <strong>sombras</strong> projetadas pelo fogo atrás deles. Eles acham que as sombras são a realidade.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><p>Um deles se solta, sai da caverna, é ofuscado pelo Sol, mas aos poucos vê o <strong>mundo real</strong> (a verdade).</p><h2>O Significado</h2><p><strong>Caverna (Mundo Sensível):</strong> Nosso mundo das aparências, das ilusões dos nossos 5 sentidos.</p><p><strong>Fora (Mundo das Ideias):</strong> Onde reside a verdadeira realidade e sabedoria.</p><p><strong>O Sol:</strong> A luz da verdade e do Bem Maior.</p>" "<ul><li>Correntes = ignorância, preconceito, tradições cegas.</li><li>Sombras = ilusões, fake news, senso comum.</li><li>O homem liberto é a figura do filósofo que busca a verdade.</li><li><strong>Dualismo:</strong> Mundo Sensível (ilusório) vs. Mundo Inteligível (verdadeiro).</li></ul>" "O que representam as correntes?" "Representam as barreiras que nos impedem de buscar a sabedoria: os dogmas, os costumes impostos e o comodismo com a ignorância." "O que acontece quando o homem que viu a luz volta à caverna?" "Na alegoria, quando ele volta para contar a verdade aos outros, os prisioneiros não acreditam nele e preferem continuar na escuridão, com medo do novo e do desconhecido." "💡"

MakeArticle "filosofia" "etica-e-moral.html" "filosofia" "Filosofia" "Ética vs Moral" "Ética vs Moral" "Entenda de uma vez a diferença conceitual entre esses termos." "50" "<p>Geralmente usados como sinônimos no dia a dia, para a filosofia, <strong>Ética e Moral</strong> são conceitos distintos.</p><h2>O que é Moral?</h2><p>Conjunto de regras, costumes, crenças e valores de uma cultura ou sociedade <strong>em determinada época</strong>. A moral dita o que é 'certo' ou 'errado' na prática.</p><p>Ex: No passado era moralmente aceitável manter escravos. Hoje não é.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>O que é Ética?</h2><p>A ética é a <strong>reflexão teórica e filosófica</strong> sobre essa moral. É o estudo de *por que* algo é considerado certo ou errado. A ética questiona a moral vigente.</p><p>A moral é a regra; a Ética é o princípio por trás da regra.</p>" "<ul><li><strong>Moral:</strong> Prática, cultural, temporal, regional.</li><li><strong>Ética:</strong> Teórica, filosófica, universal (princípios).</li><li>A Ética é colocar a moral sob avaliação da razão.</li></ul>" "A moralidade muda?" "Sim! A moral é dinâmica e muda conforme as sociedades evoluem e debatem seus valores ao longo do tempo." "Uma lei pode ser moral mas não ética?" "Sim. Uma lei pode ser aceita por uma sociedade fechada (como segregação racial no passado), portanto ser 'moral', mas através de princípios universais de direitos humanos, essa lei se prova profundamente antiética." "💡"

# Sociologia
$sociologia_arts = @(
    @{file="cultura-e-sociedade.html"; title="Cultura e Sociedade"; desc="Como a cultura molda e é moldada pelas sociedades."; xp="50"},
    @{file="desigualdade-social.html"; title="Desigualdade Social"; desc="Bases sociológicas da desigualdade."; xp="75"},
    @{file="movimentos-sociais.html"; title="Movimentos Sociais"; desc="Ação coletiva e mudanças estruturais."; xp="50"}
)
MakeLanding "sociologia" "Sociologia" "sociologia" "Entenda como a sociedade funciona e se transforma." $sociologia_arts "Entenda a Sociedade" "Estudo de caso e pontos de XP aguardam." '<svg viewBox="0 0 36 36" fill="none" style="width:48px;height:48px;vertical-align:middle;margin-right:8px"><circle cx="18" cy="12" r="5" fill="#E91E63" opacity="0.2" stroke="#E91E63" stroke-width="2"/><circle cx="10" cy="24" r="4" fill="#E91E63" opacity="0.15" stroke="#E91E63" stroke-width="1.5"/><circle cx="26" cy="24" r="4" fill="#E91E63" opacity="0.15" stroke="#E91E63" stroke-width="1.5"/><path d="M14 20c2 2 6 2 8 0" stroke="#E91E63" stroke-width="1.5"/></svg>'

MakeArticle "sociologia" "cultura-e-sociedade.html" "sociologia" "Sociologia" "Cultura e Sociedade" "Cultura e Sociedade" "Elementos da cultura material e imaterial e sua função na coesão social." "50" "<p>A <strong>Cultura</strong> é o termo guarda-chuva para os comportamentos e normas de uma <strong>Sociedade</strong>, sendo o que nos distingue dos animais.</p><h2>Tipos de Cultura</h2><p><strong>Cultura Material:</strong> Tudo o que é físico e palpável (construções, ferramentas, obras de arte, roupas e tecnologia).</p><p><strong>Cultura Imaterial:</strong> Os aspectos abstratos (linguagem, crenças, mitos, valores familiares, costumes, música e leis).</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Coesão Social</h2><p>A cultura compartilha um conjunto de significados que proporciona coesão (união) e identidade a um grupo. Sociedades precisam da cultura para funcionarem sem caos.</p>" "<ul><li>Sem sociedade, não existe cultura. Sem cultura, não haveria sociedade humana.</li><li>Relativismo cultural: não existe cultura superior nem inferior, apenas culturas diferentes.</li><li>Etnocentrismo: julgar as outras culturas usando sua própria como régua de certo/errado (evite isso!).</li></ul>" "O que é contracultura?" "É um movimento ou grupo social cujos valores e padrões de comportamento se opõem diretamente à cultura dominante (mainstream). Ex: movimento hippie nos anos 60." "Costumes e cultura são a mesma coisa?" "Os costumes (práticas repetidas do dia a dia) fazem parte da cultura, sendo um de seus aspectos imateriais mais fortes!" "👥"

MakeArticle "sociologia" "desigualdade-social.html" "sociologia" "Sociologia" "Desigualdade Social" "Desigualdade Social" "Como a riqueza e poder são distribuídos de modo desigual." "75" "<p>Diferentemente das desigualdades naturais (força, inteligência), a <strong>desigualdade social</strong> é um produto histórico e construído das interações humanas na sociedade.</p><h2>Dimensões da Desigualdade</h2><p>Não se limita apenas a dinheiro. Pode ser:</p><p><strong>Econômica:</strong> Distribuição desigual de renda e bens.</p><p><strong>Status e Poder:</strong> Distribuição desigual do prestígio político ou social.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><p><strong>Racial e Gênero:</strong> Discriminação que impede acesso a recursos iguais baseada na cor da pele ou sexo.</p><h2>Pensadores</h2><p>Para Karl Marx (marxismo), a base da desigualdade está na <strong>divisão de classes</strong> (burguesia versus proletariado) e na exploração do trabalho.</p>" "<ul><li>Fenômeno social e estrutural, construído no interior de cada sociedade.</li><li>Índice de Gini: mede a desigualdade de renda em um país (vai de 0 a 1, onde mais perto de 1 pior a distribuição).</li><li>Estratificação Social: como as sociedades dividem as pessoas em camadas.</li></ul>" "O que é meritocracia?" "A ideia de que recompensas sociais e conquistas são resultado direto do esforço (mérito) individual. O conceito é criticado na sociologia por ignorar privilégios e pontos de partida desiguais na competição." "O problema atinge apenas a economia?" "Não. A desigualdade de renda gera um leque enorme de problemas como fome, falta de acesso à saúde, analfabetismo, violência e exclusão política das minorias." "👥"

MakeArticle "sociologia" "movimentos-sociais.html" "sociologia" "Sociologia" "Movimentos Sociais" "Movimentos Sociais" "Ação coletiva por mudanças ou conservação de estruturas." "50" "<p>Os <strong>movimentos sociais</strong> são ações coletivas organizadas com objetivo de promover ou barrar mudanças na sociedade.</p><h2>Principais Características</h2><p><strong>Causa comum:</strong> Um tema que gera sentimentos de injustiça ou necessidade de progresso (direitos civis, meio ambiente).</p><p><strong>Organização:</strong> Redes de pessoas com lideranças (formais ou informais), mobilização de recursos e estratégias.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Velhos vs Novos</h2><p><strong>Clássicos:</strong> Tinham foco na economia e classes trabalhadoras (Sindicatos, Movimento Operário séc. XIX).</p><p><strong>Novos Movimentos:</strong> Foco em identidade, cultura e novos direitos (Feminista, Negro, LGBTQIAP+, Movimento Ecológico).</p>" "<ul><li>Não são ações caóticas. Têm organização e agenda.</li><li>Atuam contra e a favor do Estado para pleitear suas demandas.</li><li>A internet alterou profundamente como movimentos se organizam.</li></ul>" "Os movimentos sociais só buscam mudança?" "A grande maioria sim, mas existem movimentos sociais conservadores ou reacionários cujo único objetivo é justamente <strong>impedir</strong> e frear uma mudança cultural que eles julgam prejudicial." "O que é o ativismo de sofá?" "Critica direcionada ao ativismo apenas via internet (hashtags e curtidas), exigindo pouco engajamento real e raramente se traduzindo em mudanças políticas efetivas no mundo real." "👥"

