. .\`_generate.ps1

# Literatura
$literatura_arts = @(
    @{file="romantismo.html"; title="Romantismo"; desc="Sentimentalismo e idealização do século XIX."; xp="50"},
    @{file="realismo.html"; title="Realismo"; desc="Machado de Assis e a crítica à sociedade."; xp="75"},
    @{file="modernismo.html"; title="Modernismo"; desc="A Semana de 22 e a ruptura artística na literatura."; xp="50"}
)
MakeLanding "literatura" "Literatura" "literatura" "As principais escolas literárias brasileiras e portuguesas, direto ao ponto." $literatura_arts "Leia nas Entrelinhas" "Teste seu conhecimento de escolas literárias." '<svg viewBox="0 0 36 36" fill="none" style="width:48px;height:48px;vertical-align:middle;margin-right:8px"><path d="M6 6h10c2 0 4 2 4 4v20c-2-2-4-2-6-2H6V6z" fill="#8D6E63" opacity="0.15" stroke="#8D6E63" stroke-width="2"/><path d="M30 6H20c-2 0-4 2-4 4v20c2-2 4-2 6-2h8V6z" fill="#8D6E63" opacity="0.1" stroke="#8D6E63" stroke-width="2"/></svg>'

MakeArticle "literatura" "romantismo.html" "literatura" "Literatura" "Romantismo" "Romantismo" "Revolução emocional, gerações da poesia e autores do Brasil." "50" "<p>O <strong>Romantismo</strong> foi uma escola literária e artística do século XIX marcada pelas emoções extremas, subjetivismo e fuga da realidade.</p><h2>Linhagem Brasileira (Poesia)</h2><p><strong>1ª Geração (Indianista):</strong> Nacionalismo exaltado. O índio surge como herói nacional, uma figura nobre e mítica (ex: Gonçalves Dias e sua *Canção do Exílio*).</p><p><strong>2ª Geração (Ultrarromântica):</strong> Mal do século. Pessimismo, morte, tristeza e tédio, com muito foco na dor de amar (ex: Álvares de Azevedo).</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><p><strong>3ª Geração (Condoreira):</strong> Foco social. Luta pelas causas libertárias, forte tom oratório contra a escravidão (ex: Castro Alves, o poeta dos escravos).</p><h2>No Romance (Prosa)</h2><p>José de Alencar consagrou o romance de costumes, o regionalista e o histórico/indianista (Iracema, O Guarani).</p>" "<ul><li>Subjetivismo e Egocentrismo (triunfo do Eu).</li><li>Sentimentos à flor da pele, fuga do mundo (escapismo).</li><li>Nacionalismo como forte componente na fundação da literatura brasileira.</li></ul>" "O que era o 'mal do século'?" "A depressão, a morbidez e a negação da realidade que afetavam muitos dos poetas da segunda geração. Muitos morriam jovens (normalmente de tuberculose) pelo estilo de vida desregrado que levavam (álcool e boemia)." "Tem algo a ver com romances de amor hoje em dia?" "O uso moderno da palavra 'romântico' descende daqui, afinal, o amor intenso, impossível e idealizado era o grande tema dessas produções século XIX (o herói quase sempre sofrendo)." "📖"

MakeArticle "literatura" "realismo.html" "literatura" "Literatura" "Realismo" "Realismo" "Oposição ao romantismo, crítica social e ascensão de Machado de Assis." "75" "<p>Na segunda metade do século XIX, cansados da fantasia excessiva, os autores viraram os olhos para os defeitos práticos da sociedade com o <strong>Realismo</strong>.</p><h2>Características Principais</h2><p><strong>Foco na Objetividade e Verdade:</strong> Retrato cru da sociedade (fim da mulher idealizada romântica).</p><p><strong>Determinismo e Psicologia:</strong> O meio afeta profundamente a pessoa. Foco enorme na mente dos personagens (conflitos internos).</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><p><strong>Crítica Social:</strong> Denúncia brutal aos costumes da burguesia hipócrita: casamento por interesse, egoísmo, adultério e exploração.</p><h2>Machado de Assis</h2><p>O maior de todos! Iniciou o realismo no Brasil com <em>Memórias Póstumas de Brás Cubas</em> em 1881. Seu estilo marcante mistura pessimismo, fina ironia e quebra da quarta parede (falar com o leitor).</p>" "<ul><li>Oposição brutal e completa de todas as bases do Romantismo.</li><li>A verdade nua e o desencanto com a civilização.</li><li>O autor escreve com tom de distanciamento, como um cientista social analisando os fatos friamente.</li></ul>" "O que é o Naturalismo?" "Foi uma 'vertente exagerada' do Realismo. Se o Realismo criticava os costumes psicologicamente, o Naturalismo levava isso ao extremo biológico: achava que o homem é como um animal agindo apenas por instinto e genética (Ex: <em>O Cortiço</em>)." "Sobre o que Machado escrevia?" "Machado de Assis escrevia esmiuçando e expondo as falsidades, máscaras e invejas da elite carioca do Segundo Reinado. Seu humor era ácido como veneno, embora sofisticado e sutil." "📖"

MakeArticle "literatura" "modernismo.html" "literatura" "Literatura" "Modernismo e a Semana de 22" "Modernismo" "A mudança completa da arte nacional e as fases das gerações do modernismo." "50" "<p>O Modernismo sacudiu as artes (pintura, música e literatura) e começou de fato com a <strong>Semana de Arte Moderna em 1922</strong> em São Paulo.</p><h2>O Grande Grito: 1ª Fase (Heroica)</h2><p>Propósito principal: <strong>Destruir!</strong>. Era a fase de ruptura fortíssima com o tradicionalismo acadêmico parnasiano. Muito nacionalismo crítico (ver o Brasil e sua língua real), ironia, piada e versos livres, sem se importar com a rima clássica (ex: Mário de Andrade, Oswald de Andrade).</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>O Grande Aprofundamento: 2ª Fase</h2><p>Mais maduros, já tendo destruído a tradição em 22. Focaram no romance regionalista nordestino (a seca em Vidas Secas, Graciliano Ramos) e na poesia gigantesca e questionadora (Drummond de Andrade e Vinícius de Moraes).</p><h2>A Experimentação: 3ª Fase</h2><p>Foco na linguagem e inovações estéticas, incluindo palavras reinventadas por Guimarães Rosa e o psicológico angustiante de Clarice Lispector.</p>" "<ul><li>Fim absoluto das regras de metrificação! A poesia não tem que rimar para ser arte (verso livre/branco).</li><li>Valorização do coloquial, do linguajar do povo.</li><li>Estudar forte as características da 1ª Fase e o impacto da Semana de 22.</li></ul>" "O que queriam Oswald e Mário de Andrade (Movimento Antropofágico)?" "O Movimento sugeria que o Brasil deveria ser antropófago (canibal) cultural: 'engolir' a cultura europeia que nos é imposta, digeri-la e produzir algo novo, misturando-a e vomitando algo originalmente brasileiro!" "A Semana de Arte de 22 foi um sucesso na hora?" "Não! Foi um escândalo no Teatro Municipal. O público da elite vaiou, gritou, xingou e os jornais acharam um absurdo (afinal, era esse o exato objetivo dos pioneiros)." "📖"

# Redação
$redacao_arts = @(
    @{file="estrutura-dissertacao.html"; title="Estrutura da Dissertação"; desc="Passo a passo da dissertação-argumentativa: Introdução, Desenvolvimento e Conclusão."; xp="75"},
    @{file="como-fazer-introducao.html"; title="Como fazer uma Introdução"; desc="Tese, repertório e ganchos em 1 minuto."; xp="50"},
    @{file="conectivos.html"; title="Conectivos Essenciais"; desc="A importância da amarração entre as partes do texto."; xp="50"}
)
MakeLanding "redacao" "Redação" "redacao" "Dicas e estruturas infalíveis para conquistar a nota mil." $redacao_arts "Garanta Sua Nota" "Aprenda a escrever pra passar." '<svg viewBox="0 0 36 36" fill="none" style="width:48px;height:48px;vertical-align:middle;margin-right:8px"><path d="M8 6h20v24H8z" fill="#FF7043" opacity="0.1" stroke="#FF7043" stroke-width="2" rx="2"/><line x1="12" y1="12" x2="24" y2="12" stroke="#FF7043" stroke-width="1.5"/><line x1="12" y1="17" x2="24" y2="17" stroke="#FF7043" stroke-width="1.5"/><line x1="12" y1="22" x2="20" y2="22" stroke="#FF7043" stroke-width="1.5"/><path d="M22 20l4 4-2 2-4-4 2-2z" fill="#FF7043" opacity="0.4"/></svg>'

MakeArticle "redacao" "estrutura-dissertacao.html" "redacao" "Redação" "Estrutura da Dissertação" "A Base do Texto" "Se você quer a nota mil, você precisa dessa estrutura e não fugir disso." "75" "<p>O texto <strong>dissertativo-argumentativo</strong> (modelo Enem/Vestibulares) não aceita achismos. Ele precisa de fatos encadeados em um formato imutável.</p><h2>1. Introdução (1 parágrafo)</h2><p>Você apresenta o tema de forma abrangente com um repertório e, no fim do parágrafo, declara sua <strong>tese</strong> (a opinião clara que você defenderá). Tudo em umas 5 a 6 linhas.</p><h2>2. Desenvolvimento (2 parágrafos)</h2><p>A parte mais pesada da nota, com 7 a 8 linhas cada parágrafo (Tópico Frasal + Argumento). O Desenvolvimento 1 aborda uma causa ou o primeiro lado do problema; o Desenvolvimento 2 aborda outra causa (ou consequência) do problema.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>3. Conclusão (1 parágrafo)</h2><p>Você jamais insere novas informações/repertórios. No modelo ENEM, em umas 6 linhas, você elabora a Proposta de Intervenção: Uma sugestão detalhada para resolver ou minorar o problema (citando Quem vai fazer, O Que, Como, Pra Que e com Qual detalhamento extra).</p>" "<ul><li>4 Parágrafos redondinhos (nunca fuja dessa regra: Introdução, D1, D2, Conclusão).</li><li>Ter Repertório Sociocultural e Tese clara.</li><li>Ter um conectivo ligando os desenvolvimentos e um na conclusão (Ex: Logo, Portanto).</li></ul>" "O que zera a redação automaticamente?" "Fugir totalmente do tema ou escrever em formato errado (por exemplo, fazer um poema no lugar de uma dissertação), bem como apresentar desenhos que não condizem na folha." "Posso usar primeira pessoa ('Eu acho que')?" "DE JEITO NENHUM. O formato dissertativo-argumentativo foca na impessoalidade. Troque o 'Eu vejo que' por 'Nota-se que' e evite achismos." "✍️"

MakeArticle "redacao" "como-fazer-introducao.html" "redacao" "Redação" "Como Fazer Uma Introdução Forte" "A Introdução Perfeita" "Você tem três fases para o parágrafo inicial perfeito. Conheça as partes essenciais." "50" "<p>A introdução é o seu cartão de visitas para o avaliador. Se ela for clichê e fraca, o examinador não enxergará seu texto de modo bom. A estrutura de ouro pede três momentos (períodos) nas suas 5 ou 6 linhas.</p><h2>Fase 1: O Repertório Inicial (Gatilho)</h2><p>Traga o leitor para o tema usando uma obra (filme, série, música, momento histórico histórico ou filósofo). Ex: 'Na obra utópica Utopia de Thomas More, observamos...'</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Fase 2: A Ligação com o Tema (O Choque)</h2><p>Diga que, fora da ficção citada acima, a situação real no Brasil hoje é ou muito diferente (oposição) ou idêntica (comparação). É hora de mostrar exatamente o que a folha exigia do candidato (Contextualizar).</p><h2>Fase 3: A Tese (A Opinião Guiada)</h2><p>Bata o martelo argumentativo indicando o caminho que você vai seguir. (Ex: 'Visto isso, o problema persiste no Brasil, seja por causa da negligência estatal, ou pela ignorância social.'). Dessa forma você anuncia que o Desenvolvimento I será sobre Estado, e o Desenvolvimento II sobre a sociedade.</p>" "<ul><li>Use ao menos 3 pontos finais no parágrafo separando as fases acima.</li><li>A tese é obrigatória: deve vir na última frase do parágrafo da introdução de modo afirmativo.</li><li>Não misture repertórios. Use apenas um forte!</li></ul>" "E se eu não souber de repertório para aquele tema?" "Você pode usar um coringa histórico. A maioria dos problemas brasileiros descende do período colonial ou ditatorial; outro caminho coringa é utilizar o art 5º e art 6º da Constituição Federal que asseguram direitos básicos (educação, saúde e segurança) a todos os cidadãos (o que quase sempre é ferido na prática em qualquer tema do Enem)." "Qual o tamanho que deve ter minha introdução?" "Evite gigantes e anões. O ideal gira entre 5 e 6 linhas, que é suficiente para não estourar a página nem faltar argumento na folha de 30 espaços do Enem." "✍️"

MakeArticle "redacao" "conectivos.html" "redacao" "Redação" "Conectivos e Coesão Correta" "Uso de Conectivos" "Use essa lista para criar fluidez entre seus quatro parágrafos essenciais." "50" "<p>Os conectivos, elementos de coesão, são essenciais na redação (Competência 4 no Enem). Eles unem suas frases, seus parágrafos, suas ideias.</p><h2>Iniciando seu Desenvolvimento I</h2><p>O foco principal é afirmar. Diga que é necessário analisar a problemática em algum plano.</p><p>Exemplos: Sob esse viés, Diante desse cenário, Nesse contexto, A priori, Primordialmente, Em primeira análise.</p><div class='ad-slot ad-slot--inline'><span>Espaço Publicitário</span></div><h2>Iniciando seu Desenvolvimento II</h2><p>Muda se você for adicionar ideia semelhante (Adição) ou contradizendo a primeira causa (Oposição).</p><p>Soma: Ademais, Outrossim, Além disso, Em segunda análise, Somado a isso.</p><p>Opondo: Por outro lado, Entretanto, Porém, Contudo, Em contrapartida.</p><h2>Iniciando sua Conclusão Final</h2><p>Nunca fuja de fechar a ideia das consequências.</p><p>Use sem medo: Portanto, Logo, Depreende-se, Sendo assim, Por fim.</p>" "<ul><li>Jamais utilize gírias para conexões no seu texto, em momento algum.</li><li>Você ganha MUITA nota ao utilizar conectivos na prova (mesmo intraparágrafos entre períodos).</li><li>Não use 'Atualmente' nem 'Hoje em dia' na sua redação, evite redundâncias gigantes!</li></ul>" "Posso repetir o mesmo conectivo três vezes?" "Isso retira muitos pontos de sua coesão de vocabulário. O que difere um aluno mediano de um avançado é não travar nas mesmas três palavras. Enriqueça a sua variedade com antípodas." "Pode-se usar o 'Através' sem medo?" "Pode e deve ser evitado (prefira 'Por meio de'). A semântica original para 'Através de', seria física - de 'atravessar uma ponte, um vidro'." "✍️"
